export default {
  monsterData: [
    {
      id: 0,
      name: 'スライム',
      floor: '1~3',
      type1: '',
      type2: '',
      hp: 5,
      attack: 1,
      deffense: 1,
      exp: 2,
      level: 1,
      maxLevel: 99,
      heal: 50,
      growth: '普通早熟',
      drop: 2,
      correction: 250
    },
    {
      id: 1,
      name: 'スライムベス',
      floor: '1~4',
      type1: '',
      type2: '',
      hp: 6,
      attack: 3,
      deffense: 3,
      exp: 3,
      level: 1,
      maxLevel: 99,
      heal: 50,
      growth: '普通早熟',
      drop: 3,
      correction: 200
    },
    {
      id:         2,
      name:       'いたずらもぐら',
      floor:      '2~5',
      type1:      '剣',
      type2:      '',
      hp:         8,
      attack:     6,
      deffense:   5,
      exp:        4,
      level:      1,
      maxLevel:   5,
      heal:       50,
      growth:     '普通早熟',
      drop:       0,
      correction: 1
    },
    {
      id:         3,
      name:       'ももんじゃ',
      floor:      '3~6',
      type1:      '',
      type2:      '',
      hp:         12,
      attack:     7,
      deffense:   5,
      exp:        6,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '普通早熟',
      drop:       3,
      correction: 100
    },
    {
      id:         4,
      name:       'おおナメクジ',
      floor:      '4~7',
      type1:      '',
      type2:      '',
      hp:         17,
      attack:     8,
      deffense:   7,
      exp:        7,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       3,
      correction: 100
    },
    {
      id:         5,
      name:       'はりせんもぐら',
      floor:      '4~8',
      type1:      '炎',
      type2:      '',
      hp:         4,
      attack:     7,
      deffense:   4,
      exp:        15,
      level:      1,
      maxLevel:   9,
      heal:       50,
      growth:     '守備特殊',
      drop:       6,
      correction: -168
    },
    {
      id:         6,
      name:       'おおきづち',
      floor:      '5~8',
      type1:      '',
      type2:      '',
      hp:         15,
      attack:     10,
      deffense:   8,
      exp:        8,
      level:      1,
      maxLevel:   5,
      heal:       50,
      growth:     '防御晩成',
      drop:       8,
      correction: 1
    },
    {
      id:         7,
      name:       'オニオーン',
      floor:      '5~15',
      type1:      '',
      type2:      '',
      hp:         10,
      attack:     1,
      deffense:   1,
      exp:        1,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '守備特殊',
      drop:       30,
      correction: 5
    },
    {
      id:         8,
      name:       'ホイミスライム',
      floor:      '6~10',
      type1:      '浮',
      type2:      '',
      hp:         28,
      attack:     10,
      deffense:   9,
      exp:        11,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '普通早熟',
      drop:       0,
      correction: 50
    },
    {
      id:         9,
      name:       'ドラキー',
      floor:      '6~10',
      type1:      '浮',
      type2:      '',
      hp:         15,
      attack:     14,
      deffense:   4,
      exp:        4,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '普通早熟',
      drop:       8,
      correction: 150
    },
    {
      id:         10,
      name:       'おばけヒトデ',
      floor:      '7~11',
      type1:      '水',
      type2:      '',
      hp:         22,
      attack:     12,
      deffense:   12,
      exp:        14,
      level:      1,
      maxLevel:   5,
      heal:       50,
      growth:     '防御晩成',
      drop:       3,
      correction: 1
    },
    {
      id:         11,
      name:       'ラリホーアント',
      floor:      '7~14',
      type1:      '',
      type2:      '',
      hp:         25,
      attack:     11,
      deffense:   10,
      exp:        25,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 30
    },
    {
      id:         12,
      name:       'ゴースト',
      floor:      '8~12',
      type1:      '浮',
      type2:      '',
      hp:         21,
      attack:     9,
      deffense:   10,
      exp:        13,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       5,
      correction: 100
    },
    {
      id:         13,
      name:       'タップペンギー',
      floor:      '8~12',
      type1:      '水',
      type2:      '',
      hp:         31,
      attack:     13,
      deffense:   15,
      exp:        18,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 70
    },

  ]
}