export default {
  monsterData: [
    {
      id: 0,
      name: 'スライム',
      floor: '1~3',
      type1: '',
      type2: '',
      hp: 5,
      attack: 1,
      defense: 1,
      exp: 2,
      level: 1,
      maxLevel: 99,
      heal: 50,
      growth: '普通早熟',
      drop: 2,
      correction: 250
    },
    {
      id: 1,
      name: 'スライムベス',
      floor: '1~4',
      type1: '',
      type2: '',
      hp: 6,
      attack: 3,
      defense: 3,
      exp: 3,
      level: 1,
      maxLevel: 99,
      heal: 50,
      growth: '普通早熟',
      drop: 3,
      correction: 200
    },
    {
      id:         2,
      name:       'いたずらもぐら',
      floor:      '2~5',
      type1:      '剣',
      type2:      '',
      hp:         8,
      attack:     6,
      defense:   5,
      exp:        4,
      level:      1,
      maxLevel:   5,
      heal:       50,
      growth:     '普通早熟',
      drop:       0,
      correction: 1
    },
    {
      id:         3,
      name:       'ももんじゃ',
      floor:      '3~6',
      type1:      '',
      type2:      '',
      hp:         12,
      attack:     7,
      defense:   5,
      exp:        6,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '普通早熟',
      drop:       3,
      correction: 100
    },
    {
      id:         4,
      name:       'おおナメクジ',
      floor:      '4~7',
      type1:      '',
      type2:      '',
      hp:         17,
      attack:     8,
      defense:   7,
      exp:        7,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       3,
      correction: 100
    },
    {
      id:         5,
      name:       'はりせんもぐら',
      floor:      '4~8',
      type1:      '炎',
      type2:      '',
      hp:         4,
      attack:     7,
      defense:   4,
      exp:        15,
      level:      1,
      maxLevel:   9,
      heal:       50,
      growth:     '守備特殊',
      drop:       6,
      correction: -168
    },
    {
      id:         6,
      name:       'おおきづち',
      floor:      '5~8',
      type1:      '',
      type2:      '',
      hp:         15,
      attack:     10,
      defense:   8,
      exp:        8,
      level:      1,
      maxLevel:   5,
      heal:       50,
      growth:     '防御晩成',
      drop:       8,
      correction: 1
    },
    {
      id:         7,
      name:       'オニオーン',
      floor:      '5~15',
      type1:      '',
      type2:      '',
      hp:         10,
      attack:     1,
      defense:   1,
      exp:        1,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '守備特殊',
      drop:       30,
      correction: 5
    },
    {
      id:         8,
      name:       'ホイミスライム',
      floor:      '6~10',
      type1:      '浮',
      type2:      '',
      hp:         28,
      attack:     10,
      defense:   9,
      exp:        11,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '普通早熟',
      drop:       0,
      correction: 50
    },
    {
      id:         9,
      name:       'ドラキー',
      floor:      '6~10',
      type1:      '浮',
      type2:      '',
      hp:         15,
      attack:     14,
      defense:   4,
      exp:        4,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '普通早熟',
      drop:       8,
      correction: 150
    },
    {
      id:         10,
      name:       'おばけヒトデ',
      floor:      '7~11',
      type1:      '水',
      type2:      '',
      hp:         22,
      attack:     12,
      defense:   12,
      exp:        14,
      level:      1,
      maxLevel:   5,
      heal:       50,
      growth:     '防御晩成',
      drop:       3,
      correction: 1
    },
    {
      id:         11,
      name:       'ラリホーアント',
      floor:      '7~14',
      type1:      '',
      type2:      '',
      hp:         25,
      attack:     11,
      defense:   10,
      exp:        25,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 30
    },
    {
      id:         12,
      name:       'ゴースト',
      floor:      '8~12',
      type1:      '浮',
      type2:      '',
      hp:         21,
      attack:     9,
      defense:   10,
      exp:        13,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       5,
      correction: 100
    },
    {
      id:         13,
      name:       'タップペンギー',
      floor:      '8~12',
      type1:      '水',
      type2:      '',
      hp:         31,
      attack:     13,
      defense:   15,
      exp:        18,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 70
    },
    {
      id:         14,
      name:       'スライムブレス',
      floor:      '8~13',
      type1:      '浮',
      type2:      '炎',
      hp:         34,
      attack:     14,
      defense:   12,
      exp:        35,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       3,
      correction: 70
    },
    {
      id:         15,
      name:       'スカイフロッグ',
      floor:      '10~14',
      type1:      '水',
      type2:      '',
      hp:         38,
      attack:     9,
      defense:   10,
      exp:        10,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃晩成',
      drop:       3,
      correction: 100
    },
    {
      id:         16,
      name:       'ファーラット',
      floor:      '11~15',
      type1:      '',
      type2:      '',
      hp:         25,
      attack:     15,
      defense:   11,
      exp:        13,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       10,
      correction: 50
    },
    {
      id:         17,
      name:       'ダンスキャロット',
      floor:      '11~15',
      type1:      '',
      type2:      '',
      hp:         28,
      attack:     18,
      defense:   13,
      exp:        26,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       3,
      correction: 100
    },
    {
      id:         18,
      name:       'つのうしがい',
      floor:      '11~15',
      type1:      '水',
      type2:      '',
      hp:         27,
      attack:     18,
      defense:   16,
      exp:        24,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 100
    },
    {
      id:         19,
      name:       'あめふらし',
      floor:      '12~15',
      type1:      '',
      type2:      '',
      hp:         31,
      attack:     19,
      defense:   14,
      exp:        35,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       6,
      correction: 70
    },
    {
      id:         20,
      name:       'あやしいかげ',
      floor:      '13~15',
      type1:      '浮',
      type2:      '',
      hp:         5,
      attack:     20,
      defense:   1,
      exp:        25,
      level:      1,
      maxLevel:   9,
      heal:       50,
      growth:     '守備特殊',
      drop:       0,
      correction: -178
    },
    {
      id:         21,
      name:       'リリパット',
      floor:      '16~17',
      type1:      '',
      type2:      '',
      hp:         40,
      attack:     11,
      defense:   12,
      exp:        26,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       8,
      correction: 100
    },
    {
      id:         22,
      name:       'スモールグール',
      floor:      '16~19',
      type1:      '',
      type2:      '',
      hp:         55,
      attack:     17,
      defense:   10,
      exp:        22,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃早熟',
      drop:       2,
      correction: 100
    },
    {
      id:         23,
      name:       'ゴーレム(PS2)',
      floor:      '16~20',
      type1:      '',
      type2:      '',
      hp:         55,
      attack:     30,
      defense:   22,
      exp:        75,
      level:      2,
      maxLevel:   99,
      heal:       100,
      growth:     '万能晩成',
      drop:       0,
      correction: 100,
      gbaId:      24
    },
    {
      id:         24,
      name:       'ゴーレム(GBA)',
      floor:      '16~20',
      type1:      '',
      type2:      '',
      hp:         55,
      attack:     33,
      defense:   23,
      exp:        75,
      level:      2,
      maxLevel:   99,
      heal:       100,
      growth:     '万能晩成',
      drop:       0,
      correction: 100,
      ps2Id:      23
    },
    {
      id:         25,
      name:       'さそりかまきり',
      floor:      '16~20',
      type1:      '',
      type2:      '',
      hp:         23,
      attack:     21,
      defense:   14,
      exp:        26,
      level:      3,
      maxLevel:   99,
      heal:       100,
      growth:     '防御早熟',
      drop:       15,
      correction: 100
    },
    {
      id:         26,
      name:       'メイジももんじゃ',
      floor:      '16~20',
      type1:      '',
      type2:      '',
      hp:         45,
      attack:     19,
      defense:   19,
      exp:        35,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '普通早熟',
      drop:       3,
      correction: 50
    },
    {
      id:         27,
      name:       'キメラ',
      floor:      '17~22',
      type1:      '浮',
      type2:      '',
      hp:         48,
      attack:     30,
      defense:   20,
      exp:        75,
      level:      1,
      maxLevel:   99,
      heal:       30,
      growth:     '攻撃早熟',
      drop:       0,
      correction: 100
    },
    {
      id:         28,
      name:       'ハエまどう',
      floor:      '18~20',
      type1:      '杖',
      type2:      '',
      hp:         50,
      attack:     16,
      defense:   24,
      exp:        35,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '普通早熟',
      drop:       0,
      correction: 50
    },
    {
      id:         29,
      name:       'ドッグスナイパー',
      floor:      '18~20',
      type1:      '浮',
      type2:      '剣',
      hp:         50,
      attack:     15,
      defense:   15,
      exp:        110,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       3,
      correction: 20
    },
    {
      id:         30,
      name:       'さつじんき',
      floor:      '18~22',
      type1:      '剣',
      type2:      '',
      hp:         51,
      attack:     18,
      defense:   20,
      exp:        45,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃早熟',
      drop:       0,
      correction: 50
    },
    {
      id:         31,
      name:       'キラーマシン',
      floor:      '21~25',
      type1:      '人',
      type2:      '剣',
      hp:         60,
      attack:     20,
      defense:   25,
      exp:        80,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       4,
      correction: 100
    },
    {
      id:         32,
      name:       'スペクテット',
      floor:      '21~25',
      type1:      '',
      type2:      '',
      hp:         45,
      attack:     10,
      defense:   15,
      exp:        25,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       3,
      correction: 20
    },
    {
      id:         33,
      name:       'トロル',
      floor:      '21~25',
      type1:      '剣',
      type2:      '',
      hp:         50,
      attack:     23,
      defense:   23,
      exp:        65,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃早熟',
      drop:       3,
      correction: 100
    },
    {
      id:         34,
      name:       'シルバーデビル',
      floor:      '21~25',
      type1:      '悪',
      type2:      '',
      hp:         65,
      attack:     20,
      defense:   20,
      exp:        125,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       0,
      correction: 40
    },
    {
      id:         35,
      name:       'ひょうがまじん',
      floor:      '21~25',
      type1:      '',
      type2:      '',
      hp:         70,
      attack:     30,
      defense:   20,
      exp:        150,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃晩成',
      drop:       0,
      correction: 30
    },
    {
      id:         36,
      name:       'バブルスライム',
      floor:      '21~25',
      type1:      '',
      type2:      '',
      hp:         35,
      attack:     26,
      defense:   15,
      exp:        36,
      level:      5,
      maxLevel:   5,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 1
    },
    {
      id:         37,
      name:       'ゾンビマスター',
      floor:      '26~30',
      type1:      '屍',
      type2:      '杖',
      hp:         55,
      attack:     23,
      defense:   18,
      exp:        60,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       25,
      correction: 100
    },
    {
      id:         38,
      name:       'ミイラおとこ',
      floor:      '26~30',
      type1:      '屍',
      type2:      '',
      hp:         45,
      attack:     23,
      defense:   15,
      exp:        57,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃早熟',
      drop:       35,
      correction: 100
    },
    {
      id:         39,
      name:       'マミー',
      floor:      '26~30',
      type1:      '屍',
      type2:      '',
      hp:         43,
      attack:     27,
      defense:   15,
      exp:        67,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃早熟',
      drop:       35,
      correction: 100
    },
    {
      id:         40,
      name:       'リビングデッド',
      floor:      '26~30',
      type1:      '屍',
      type2:      '',
      hp:         50,
      attack:     15,
      defense:   16,
      exp:        45,
      level:      1,
      maxLevel:   9,
      heal:       50,
      growth:     '普通早熟',
      drop:       30,
      correction: 100
    },
    {
      id:         41,
      name:       'うごくせきぞう',
      floor:      '26~35',
      type1:      '人',
      type2:      '',
      hp:         42,
      attack:     20,
      defense:   22,
      exp:        43,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         42,
      name:       'レノファイター',
      floor:      '26~35',
      type1:      '剣',
      type2:      '',
      hp:         75,
      attack:     31,
      defense:   29,
      exp:        150,
      level:      2,
      maxLevel:   99,
      heal:       100,
      growth:     '万能晩成',
      drop:       15,
      correction: 100
    },
    {
      id:         43,
      name:       'くさった死体',
      floor:      '26~35',
      type1:      '屍',
      type2:      '',
      hp:         53,
      attack:     24,
      defense:   17,
      exp:        60,
      level:      2,
      maxLevel:   9,
      heal:       50,
      growth:     '普通早熟',
      drop:       30,
      correction: 100
    },
    {
      id:         44,
      name:       'マドハンド',
      floor:      '26~35',
      type1:      '',
      type2:      '',
      hp:         10,
      attack:     6,
      defense:   11,
      exp:        18,
      level:      3,
      maxLevel:   99,
      heal:       30,
      growth:     '守備特殊',
      drop:       0,
      correction: 10
    },
    {
      id:         45,
      name:       'おばけキノコ',
      floor:      '31~35',
      type1:      '',
      type2:      '',
      hp:         46,
      attack:     22,
      defense:   18,
      exp:        54,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       2,
      correction: 80
    },
    {
      id:         46,
      name:       'シャーマン',
      floor:      '31~35',
      type1:      '屍',
      type2:      '杖',
      hp:         43,
      attack:     22,
      defense:   23,
      exp:        67,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       25,
      correction: 100
    },
    {
      id:         47,
      name:       'がいこつけんし',
      floor:      '31~35',
      type1:      '屍',
      type2:      '剣',
      hp:         43,
      attack:     29,
      defense:   12,
      exp:        58,
      level:      2,
      maxLevel:   9,
      heal:       50,
      growth:     '普通早熟',
      drop:       20,
      correction: 100
    },
    {
      id:         48,
      name:       'バーサーカー',
      floor:      '31~35',
      type1:      '屍',
      type2:      '剣',
      hp:         33,
      attack:     17,
      defense:   13,
      exp:        75,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃晩成',
      drop:       24,
      correction: 100
    },
    {
      id:         49,
      name:       'さまようよろい',
      floor:      '36~40',
      type1:      '剣',
      type2:      '',
      hp:         60,
      attack:     25,
      defense:   34,
      exp:        98,
      level:      3,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         50,
      name:       'どろにんぎょう',
      floor:      '36~40',
      type1:      '人',
      type2:      '',
      hp:         35,
      attack:     20,
      defense:   10,
      exp:        40,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 30
    },
    {
      id:         51,
      name:       'ミステリードール',
      floor:      '36~40',
      type1:      '浮',
      type2:      '人',
      hp:         60,
      attack:     23,
      defense:   17,
      exp:        55,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       3,
      correction: 10
    },
    {
      id:         52,
      name:       'ベビーサタン',
      floor:      '36~40',
      type1:      '悪',
      type2:      '剣',
      hp:         44,
      attack:     10,
      defense:   15,
      exp:        40,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 50
    },
    {
      id:         53,
      name:       'まどうし',
      floor:      '36~40',
      type1:      '杖',
      type2:      '',
      hp:         50,
      attack:     18,
      defense:   24,
      exp:        70,
      level:      3,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       8,
      correction: 50
    },
    {
      id:         54,
      name:       'げんじゅつし',
      floor:      '36~40',
      type1:      '杖',
      type2:      '',
      hp:         52,
      attack:     22,
      defense:   27,
      exp:        70,
      level:      3,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       3,
      correction: 70
    },
    {
      id:         55,
      name:       'はねせんにん',
      floor:      '36~40',
      type1:      '杖',
      type2:      '',
      hp:         47,
      attack:     19,
      defense:   34,
      exp:        49,
      level:      6,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         56,
      name:       'テンツク',
      floor:      '36~40',
      type1:      '',
      type2:      '',
      hp:         50,
      attack:     21,
      defense:   30,
      exp:        56,
      level:      3,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       8,
      correction: 100
    },
    {
      id:         57,
      name:       'ヘルゴースト',
      floor:      '41~45',
      type1:      '浮',
      type2:      '',
      hp:         50,
      attack:     24,
      defense:   23,
      exp:        112,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       3,
      correction: 100
    },
    {
      id:         58,
      name:       'ゆうれい',
      floor:      '41~45',
      type1:      '浮',
      type2:      '剣',
      hp:         29,
      attack:     22,
      defense:   9,
      exp:        30,
      level:      3,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃早熟',
      drop:       0,
      correction: 50
    },
    {
      id:         59,
      name:       'シャドー',
      floor:      '41~45',
      type1:      '浮',
      type2:      '',
      hp:         5,
      attack:     13,
      defense:   7,
      exp:        88,
      level:      3,
      maxLevel:   9,
      heal:       50,
      growth:     '守備特殊',
      drop:       0,
      correction: -178
    },
    {
      id:         60,
      name:       'ドラキーマ',
      floor:      '41~45',
      type1:      '浮',
      type2:      '',
      hp:         57,
      attack:     34,
      defense:   18,
      exp:        72,
      level:      3,
      maxLevel:   99,
      heal:       100,
      growth:     '普通早熟',
      drop:       0,
      correction: 20
    },
    {
      id:         61,
      name:       'メイジキメラ',
      floor:      '41~45',
      type1:      '浮',
      type2:      '',
      hp:         64,
      attack:     32,
      defense:   22,
      exp:        150,
      level:      2,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 40
    },
    {
      id:         62,
      name:       'おおめだま',
      floor:      '41~45',
      type1:      '',
      type2:      '',
      hp:         70,
      attack:     26,
      defense:   33,
      exp:        176,
      level:      3,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       3,
      correction: 20
    },
    {
      id:         63,
      name:       'ラストテンツク',
      floor:      '41~45',
      type1:      '',
      type2:      '',
      hp:         95,
      attack:     28,
      defense:   26,
      exp:        152,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       8,
      correction: 30
    },
    {
      id:         64,
      name:       'ガニラス',
      floor:      '46~50',
      type1:      '水',
      type2:      '',
      hp:         44,
      attack:     31,
      defense:   21,
      exp:        50,
      level:      4,
      maxLevel:   99,
      heal:       100,
      growth:     '防御早熟',
      drop:       4,
      correction: 100
    },
    {
      id:         65,
      name:       'ぐんたいガニ',
      floor:      '46~50',
      type1:      '水',
      type2:      '',
      hp:         58,
      attack:     37,
      defense:   25,
      exp:        125,
      level:      4,
      maxLevel:   99,
      heal:       100,
      growth:     '防御早熟',
      drop:       4,
      correction: 50
    },
    {
      id:         66,
      name:       'しびれマイマイ',
      floor:      '46~50',
      type1:      '水',
      type2:      '',
      hp:         39,
      attack:     28,
      defense:   24,
      exp:        42,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 100
    },
    {
      id:         67,
      name:       'アイアンタートル',
      floor:      '46~50',
      type1:      '水',
      type2:      '',
      hp:         41,
      attack:     32,
      defense:   25,
      exp:        25,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 50
    },
    {
      id:         68,
      name:       '岩とびあくま',
      floor:      '46~50',
      type1:      '水',
      type2:      '',
      hp:         43,
      attack:     29,
      defense:   24,
      exp:        47,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 70
    },
    {
      id:         69,
      name:       'マージスター',
      floor:      '46~50',
      type1:      '水',
      type2:      '',
      hp:         37,
      attack:     29,
      defense:   19,
      exp:        42,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 70
    },
    {
      id:         70,
      name:       'グレイトマーマン(PS2)',
      floor:      '46~50',
      type1:      '浮',
      type2:      '剣',
      hp:         48,
      attack:     32,
      defense:   21,
      exp:        75,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃晩成',
      drop:       0,
      correction: 100,
      gbaId:      71
    },
    {
      id:         71,
      name:       'グレイトマーマン(GBA)',
      floor:      '46~50',
      type1:      '浮',
      type2:      '剣',
      hp:         48,
      attack:     31,
      defense:   22,
      exp:        75,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃晩成',
      drop:       0,
      correction: 100,
      ps2Id:      70
    },
    {
      id:         72,
      name:       'デビルアンカー',
      floor:      '46~50',
      type1:      '水',
      type2:      '爆',
      hp:         66,
      attack:     34,
      defense:   17,
      exp:        47,
      level:      4,
      maxLevel:   99,
      heal:       100,
      growth:     '普通早熟',
      drop:       0,
      correction: 100
    },
    {
      id:         73,
      name:       'おどる宝石',
      floor:      '51~59',
      type1:      '',
      type2:      '',
      hp:         47,
      attack:     24,
      defense:   14,
      exp:        45,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 30
    },
    {
      id:         74,
      name:       'エリミネーター',
      floor:      '51~59',
      type1:      '剣',
      type2:      '',
      hp:         100,
      attack:     30,
      defense:   35,
      exp:        1050,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃早熟',
      drop:       12,
      correction: 10
    },
    {
      id:         75,
      name:       'シャドーナイト',
      floor:      '51~59',
      type1:      '浮',
      type2:      '剣',
      hp:         78,
      attack:     29,
      defense:   35,
      exp:        143,
      level:      6,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 40
    },
    {
      id:         76,
      name:       'あくましんかん',
      floor:      '51~59',
      type1:      '悪',
      type2:      '剣',
      hp:         60,
      attack:     36,
      defense:   19,
      exp:        123,
      level:      5,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃晩成',
      drop:       3,
      correction: 100
    },
    {
      id:         77,
      name:       'デーモントード',
      floor:      '51~59',
      type1:      '水',
      type2:      '悪',
      hp:         54,
      attack:     33,
      defense:   22,
      exp:        125,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         78,
      name:       'だいまどう',
      floor:      '51~59',
      type1:      '杖',
      type2:      '',
      hp:         62,
      attack:     23,
      defense:   32,
      exp:        120,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       12,
      correction: 20
    },
    {
      id:         79,
      name:       'メガザルロック',
      floor:      '51~75',
      type1:      '爆',
      type2:      '',
      hp:         55,
      attack:     36,
      defense:   21,
      exp:        92,
      level:      7,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 100
    },
    {
      id:         80,
      name:       'きとうし',
      floor:      '53~62',
      type1:      '杖',
      type2:      '',
      hp:         60,
      attack:     14,
      defense:   25,
      exp:        100,
      level:      4,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       2,
      correction: 15
    },
    {
      id:         81,
      name:       'グレイトホーン',
      floor:      '56~80',
      type1:      '剣',
      type2:      '',
      hp:         85,
      attack:     38,
      defense:   31,
      exp:        225,
      level:      2,
      maxLevel:   99,
      heal:       100,
      growth:     '万能晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         82,
      name:       'モシャスナイト',
      floor:      '58~65',
      type1:      '剣',
      type2:      '',
      hp:         66,
      attack:     24,
      defense:   33,
      exp:        140,
      level:      3,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 40
    },
    {
      id:         83,
      name:       'キラーアーマー',
      floor:      '60~65',
      type1:      '剣',
      type2:      '',
      hp:         70,
      attack:     29,
      defense:   37,
      exp:        150,
      level:      3,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       0,
      correction: 50
    },
    {
      id:         84,
      name:       'ギガンテス(PS2)',
      floor:      '60~65',
      type1:      '',
      type2:      '',
      hp:         75,
      attack:     48,
      defense:   30,
      exp:        195,
      level:      5,
      maxLevel:   99,
      heal:       50,
      growth:     '万能晩成',
      drop:       5,
      correction: 100,
      gbaId:      85
    },
    {
      id:         85,
      name:       'ギガンテス(GBA)',
      floor:      '60~65',
      type1:      '',
      type2:      '',
      hp:         75,
      attack:     51,
      defense:   32,
      exp:        195,
      level:      5,
      maxLevel:   99,
      heal:       50,
      growth:     '万能晩成',
      drop:       5,
      correction: 100,
      ps2Id:      84
    },
    {
      id:         86,
      name:       'フライングデビル',
      floor:      '60~65',
      type1:      '浮',
      type2:      '悪',
      hp:         130,
      attack:     40,
      defense:   40,
      exp:        1200,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         87,
      name:       'デビルロード',
      floor:      '60~65',
      type1:      '悪',
      type2:      '',
      hp:         120,
      attack:     25,
      defense:   35,
      exp:        1100,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       25,
      correction: 10
    },
    {
      id:         88,
      name:       'アークデーモン(PS2)',
      floor:      '60~65',
      type1:      '悪',
      type2:      '',
      hp:         80,
      attack:     52,
      defense:   35,
      exp:        243,
      level:      5,
      maxLevel:   99,
      heal:       100,
      growth:     '万能晩成',
      drop:       8,
      correction: 100,
      gbaId:      89
    },
    {
      id:         89,
      name:       'アークデーモン(GBA)',
      floor:      '60~65',
      type1:      '悪',
      type2:      '',
      hp:         80,
      attack:     52,
      defense:   37,
      exp:        243,
      level:      5,
      maxLevel:   99,
      heal:       100,
      growth:     '万能晩成',
      drop:       8,
      correction: 100,
      gbaId:      88
    },
    {
      id:         90,
      name:       'ばくだん岩',
      floor:      '66~70',
      type1:      '爆',
      type2:      '',
      hp:         126,
      attack:     23,
      defense:   23,
      exp:        150,
      level:      5,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         91,
      name:       'リビングハンマー',
      floor:      '66~70',
      type1:      '爆',
      type2:      '',
      hp:         90,
      attack:     44,
      defense:   30,
      exp:        980,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '普通早熟',
      drop:       0,
      correction: 40
    },
    {
      id:         92,
      name:       'いしにんぎょう',
      floor:      '66~70',
      type1:      '浮',
      type2:      '人',
      hp:         100,
      attack:     45,
      defense:   45,
      exp:        800,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       3,
      correction: 10
    },
    {
      id:         93,
      name:       'だいまじん',
      floor:      '66~70',
      type1:      '人',
      type2:      '',
      hp:         135,
      attack:     44,
      defense:   51,
      exp:        560,
      level:      6,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       0,
      correction: 5
    },
    {
      id:         94,
      name:       'ブラッドハンド',
      floor:      '66~70',
      type1:      '',
      type2:      '',
      hp:         26,
      attack:     17,
      defense:   21,
      exp:        50,
      level:      3,
      maxLevel:   99,
      heal:       50,
      growth:     '守備特殊',
      drop:       0,
      correction: 10
    },
    {
      id:         95,
      name:       'タマゴロン',
      floor:      '66~70',
      type1:      '',
      type2:      '',
      hp:         6,
      attack:     10,
      defense:   3,
      exp:        100,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       0,
      correction: 10
    },
    {
      id:         96,
      name:       'ファイヤーケロッグ',
      floor:      '71~75',
      type1:      '水',
      type2:      '炎',
      hp:         73,
      attack:     38,
      defense:   22,
      exp:        84,
      level:      7,
      maxLevel:   9,
      heal:       50,
      growth:     '普通早熟',
      drop:       0,
      correction: 100
    },
    {
      id:         97,
      name:       'サンダーラット',
      floor:      '71~75',
      type1:      '炎',
      type2:      '',
      hp:         6,
      attack:     12,
      defense:   22,
      exp:        160,
      level:      7,
      maxLevel:   9,
      heal:       150,
      growth:     '守備特殊',
      drop:       6,
      correction: -168
    },
    {
      id:         98,
      name:       'プラズママウス',
      floor:      '71~75',
      type1:      '炎',
      type2:      '',
      hp:         6,
      attack:     40,
      defense:   4,
      exp:        250,
      level:      1,
      maxLevel:   9,
      heal:       150,
      growth:     '守備特殊',
      drop:       6,
      correction: -168
    },
    {
      id:         99,
      name:       'ドラゴスライム',
      floor:      '71~75',
      type1:      '浮',
      type2:      '炎',
      hp:         57,
      attack:     41,
      defense:   30,
      exp:        148,
      level:      7,
      maxLevel:   99,
      heal:       150,
      growth:     '防御早熟',
      drop:       3,
      correction: 70
    },
    {
      id:         100,
      name:       'ドラゴン',
      floor:      '74~80',
      type1:      '炎',
      type2:      '',
      hp:         123,
      attack:     45,
      defense:   37,
      exp:        750,
      level:      2,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃晩成',
      drop:       0,
      correction: 30
    },
    {
      id:         101,
      name:       'ようがんまじん',
      floor:      '76~80',
      type1:      '爆',
      type2:      '',
      hp:         109,
      attack:     45,
      defense:   40,
      exp:        750,
      level:      5,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃晩成',
      drop:       0,
      correction: 30
    },
    {
      id:         102,
      name:       'ドラゴメタル',
      floor:      '76~80',
      type1:      '浮',
      type2:      '炎',
      hp:         64,
      attack:     42,
      defense:   58,
      exp:        600,
      level:      5,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       2,
      correction: 60
    },
    {
      id:         103,
      name:       'ベビーニュート',
      floor:      '76~80',
      type1:      '炎',
      type2:      '',
      hp:         50,
      attack:     23,
      defense:   35,
      exp:        66,
      level:      6,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         104,
      name:       'ドラゴンキッズ',
      floor:      '76~80',
      type1:      '炎',
      type2:      '',
      hp:         85,
      attack:     28,
      defense:   39,
      exp:        164,
      level:      6,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         105,
      name:       'メラリザード',
      floor:      '76~80',
      type1:      '炎',
      type2:      '',
      hp:         120,
      attack:     39,
      defense:   48,
      exp:        560,
      level:      6,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 100
    },
    {
      id:         106,
      name:       'スターキメラ',
      floor:      '81~89',
      type1:      '浮',
      type2:      '',
      hp:         89,
      attack:     40,
      defense:   39,
      exp:        645,
      level:      5,
      maxLevel:   99,
      heal:       30,
      growth:     '攻撃早熟',
      drop:       0,
      correction: 100
    },
    {
      id:         107,
      name:       'じごくのよろい',
      floor:      '81~99',
      type1:      '剣',
      type2:      '',
      hp:         105,
      attack:     45,
      defense:   47,
      exp:        1100,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       2,
      correction: 20
    },
    {
      id:         108,
      name:       'キラープラスター',
      floor:      '81~99',
      type1:      '剣',
      type2:      '',
      hp:         135,
      attack:     55,
      defense:   52,
      exp:        1950,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       0,
      correction: 20
    },
    {
      id:         109,
      name:       'ようじゅつし',
      floor:      '81~99',
      type1:      '杖',
      type2:      '',
      hp:         60,
      attack:     20,
      defense:   33,
      exp:        90,
      level:      5,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       2,
      correction: 15
    },
    {
      id:         110,
      name:       'キラースター',
      floor:      '81~99',
      type1:      '爆',
      type2:      '',
      hp:         88,
      attack:     40,
      defense:   26,
      exp:        165,
      level:      5,
      maxLevel:   99,
      heal:       100,
      growth:     '普通早熟',
      drop:       0,
      correction: 40
    },
    {
      id:         111,
      name:       'デスマシーン',
      floor:      '81~99',
      type1:      '悪',
      type2:      '剣',
      hp:         128,
      attack:     65,
      defense:   53,
      exp:        2100,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       0,
      correction: 30
    },
    {
      id:         112,
      name:       'ランガー',
      floor:      '81~99',
      type1:      '浮',
      type2:      '悪',
      hp:         140,
      attack:     51,
      defense:   45,
      exp:        1500,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       0,
      correction: 40
    },
    {
      id:         113,
      name:       'ダースドラゴン',
      floor:      '90~99',
      type1:      '炎',
      type2:      '',
      hp:         150,
      attack:     50,
      defense:   55,
      exp:        2400,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃晩成',
      drop:       80,
      correction: 1
    },
    {
      id:         114,
      name:       'コロマージ',
      floor:      '97~99',
      type1:      '杖',
      type2:      '',
      hp:         35,
      attack:     10,
      defense:   16,
      exp:        22,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       0,
      correction: 5
    },
    {
      id:         115,
      name:       'ミミック',
      floor:      '',
      type1:      '',
      type2:      '',
      hp:         50,
      attack:     10,
      defense:   15,
      exp:        6,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃晩成',
      drop:       0,
      correction: 10
    },
    {
      id:         116,
      name:       'ひとくいばこ',
      floor:      '',
      type1:      '',
      type2:      '',
      hp:         20,
      attack:     40,
      defense:   10,
      exp:        150,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃晩成',
      drop:       0,
      correction: 1
    },
    {
      id:         180,
      name:       'ガーゴイル',
      floor:      '3~99',
      type1:      '浮',
      type2:      '剣',
      hp:         200,
      attack:     180,
      defense:    150,
      exp:        1,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       0,
      correction: -200
    }
  ]
}