export default {
  monsterDataGBA: [
    // アンチマジックハウス
    {
      id:         115,
      name:       'じごくのハサミ',
      floor:      '?',
      type1:      '水',
      type2:      '',
      hp:         35,
      attack:     17,
      deffense:   18,
      exp:        25,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御早熟',
      drop:       '?',
      correction: 100
    },
    {
      id:         116,
      name:       'ジャスティス兄',
      floor:      '?',
      type1:      '浮',
      type2:      '',
      hp:         150,
      attack:     80,
      deffense:   80,
      exp:        1800,
      level:      1,
      maxLevel:   99,
      heal:       150,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -50
    },
    {
      id:         117,
      name:       'ランドアーマー',
      floor:      '?',
      type1:      '水',
      type2:      '',
      hp:         31,
      attack:     20,
      deffense:   35,
      exp:        15,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 50
    },
    // かっとびハウス
    {
      id:         118,
      name:       'マンドラゴラ',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         75,
      attack:     25,
      deffense:   28,
      exp:        100,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 100
    },
    {
      id:         119,
      name:       'メトロゴースト',
      floor:      '?',
      type1:      '浮',
      type2:      '',
      hp:         41,
      attack:     13,
      deffense:   18,
      exp:        35,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 100
    },
    // 気まぐれハウス
    {
      id:         120,
      name:       'しにがみ',
      floor:      '?',
      type1:      '浮',
      type2:      '剣',
      hp:         35,
      attack:     15,
      deffense:   13,
      exp:        31,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃早熟',
      drop:       '?',
      correction: 50
    },
    {
      id:         121,
      name:       'タホドラキー',
      floor:      '?',
      type1:      '浮',
      type2:      '',
      hp:         35,
      attack:     16,
      deffense:   15,
      exp:        23,
      level:      1,
      maxLevel:   3,
      heal:       50,
      growth:     '普通早熟',
      drop:       '?',
      correction: 1
    },
    {
      id:         122,
      name:       'ベホマスライム',
      floor:      '?',
      type1:      '浮',
      type2:      '',
      hp:         35,
      attack:     20,
      deffense:   10,
      exp:        20,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 30
    },
    // ケンゴウハウス
    {
      id:         123,
      name:       'エビルエスターク',
      floor:      '?',
      type1:      '悪',
      type2:      '剣',
      hp:         145,
      attack:     60,
      deffense:   55,
      exp:        1790,
      level:      1,
      maxLevel:   10,
      heal:       100,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -208
    },
    {
      id:         124,
      name:       'かげのきし',
      floor:      '?',
      type1:      '屍',
      type2:      '剣',
      hp:         85,
      attack:     30,
      deffense:   29,
      exp:        165,
      level:      1,
      maxLevel:   9,
      heal:       50,
      growth:     '普通早熟',
      drop:       '?',
      correction: 50
    },
    {
      id:         125,
      name:       'こうてつまじん',
      floor:      '?',
      type1:      '悪',
      type2:      '剣',
      hp:         135,
      attack:     60,
      deffense:   55,
      exp:        1780,
      level:      1,
      maxLevel:   10,
      heal:       100,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -108
    },
    {
      id:         126,
      name:       'しりょうのきし',
      floor:      '?',
      type1:      '屍',
      type2:      '剣',
      hp:         70,
      attack:     35,
      deffense:   35,
      exp:        350,
      level:      1,
      maxLevel:   9,
      heal:       50,
      growth:     '普通早熟',
      drop:       '?',
      correction: 50
    },
    {
      id:         127,
      name:       'どぐう戦士',
      floor:      '?',
      type1:      '剣',
      type2:      '',
      hp:         120,
      attack:     39,
      deffense:   50,
      exp:        750,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       '?',
      correction: 80
    },
    {
      id:         128,
      name:       'メタルハンター',
      floor:      '?',
      type1:      '人',
      type2:      '剣',
      hp:         130,
      attack:     40,
      deffense:   45,
      exp:        1500,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       '?',
      correction: 30
    },
    // コロプチハウス
    {
      id:         129,
      name:       'コロヒーロー',
      floor:      '?',
      type1:      '剣',
      type2:      '',
      hp:         34,
      attack:     9,
      deffense:   14,
      exp:        20,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 5
    },
    {
      id:         130,
      name:       'コロファイター',
      floor:      '?',
      type1:      '剣',
      type2:      '',
      hp:         35,
      attack:     10,
      deffense:   15,
      exp:        21,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 5
    },
    {
      id:         131,
      name:       'コロプリースト',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         35,
      attack:     11,
      deffense:   14,
      exp:        23,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 5
    },
    {
      id:         132,
      name:       'プチヒーロー',
      floor:      '?',
      type1:      '剣',
      type2:      '',
      hp:         35,
      attack:     10,
      deffense:   15,
      exp:        20,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 5
    },
    {
      id:         133,
      name:       'プチファイター',
      floor:      '?',
      type1:      '剣',
      type2:      '',
      hp:         35,
      attack:     11,
      deffense:   14,
      exp:        21,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 5
    },
    {
      id:         134,
      name:       'プチプリースト',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         33,
      attack:     10,
      deffense:   14,
      exp:        15,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 5
    },
    {
      id:         135,
      name:       'プチマージ',
      floor:      '?',
      type1:      '杖',
      type2:      '',
      hp:         20,
      attack:     8,
      deffense:   10,
      exp:        5,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 5
    },
    // 水中ハウス
    {
      id:         136,
      name:       'あんこくつむり',
      floor:      '?',
      type1:      '水',
      type2:      '',
      hp:         30,
      attack:     20,
      deffense:   19,
      exp:        35,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 100
    },
    // スライムハウス
    {
      id:         137,
      name:       'キングスライム',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         100,
      attack:     50,
      deffense:   50,
      exp:        750,
      level:      1,
      maxLevel:   10,
      heal:       100,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -208
    },
    {
      id:         138,
      name:       'ゴールデンスライム',
      floor:      '?',
      type1:      '浮',
      type2:      '',
      hp:         132,
      attack:     50,
      deffense:   50,
      exp:        1300,
      level:      1,
      maxLevel:   10,
      heal:       50,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -108
    },
    {
      id:         139,
      name:       'しびれくらげ',
      floor:      '?',
      type1:      '浮',
      type2:      '',
      hp:         31,
      attack:     10,
      deffense:   12,
      exp:        11,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 30
    },
    {
      id:         140,
      name:       'スライムエンペラー',
      floor:      '?',
      type1:      '浮',
      type2:      '',
      hp:         135,
      attack:     51,
      deffense:   51,
      exp:        1400,
      level:      1,
      maxLevel:   10,
      heal:       100,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -208
    },
    {
      id:         141,
      name:       'スライムベホマズン',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         100,
      attack:     50,
      deffense:   50,
      exp:        1000,
      level:      1,
      maxLevel:   9,
      heal:       100,
      growth:     '普通早熟',
      drop:       '?',
      correction: 1
    },
    {
      id:         142,
      name:       'はぐれメタル',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         5,
      attack:     10,
      deffense:   200,
      exp:        200,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '守備特殊',
      drop:       '?',
      correction: 1
    },
    {
      id:         143,
      name:       'プラチナキング',
      floor:      '?',
      type1:      '浮',
      type2:      '',
      hp:         134,
      attack:     52,
      deffense:   52,
      exp:        1500,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '普通早熟',
      drop:       '?',
      correction: 1
    },
    {
      id:         144,
      name:       'メタルキング',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         50,
      attack:     10,
      deffense:   100,
      exp:        1250,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '守備特殊',
      drop:       '?',
      correction: 1
    },
    {
      id:         145,
      name:       'メタルスライム',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         6,
      attack:     10,
      deffense:   100,
      exp:        100,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '守備特殊',
      drop:       '?',
      correction: 1
    },
    // 増殖ハウス
    {
      id:         146,
      name:       'エビルポット',
      floor:      '?',
      type1:      '浮',
      type2:      '悪',
      hp:         26,
      attack:     8,
      deffense:   11,
      exp:        20,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 155
    },
    {
      id:         147,
      name:       'ぐんたいアリ',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         40,
      attack:     8,
      deffense:   11,
      exp:        12,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 20
    },
    {
      id:         148,
      name:       'ベロベロ',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         80,
      attack:     45,
      deffense:   30,
      exp:        350,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃早熟',
      drop:       '?',
      correction: 50
    },
    {
      id:         149,
      name:       'ワンダーエッグ',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         6,
      attack:     10,
      deffense:   3,
      exp:        115,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 10
    },
    // ゾンビハウス
    {
      id:         150,
      name:       'グール',
      floor:      '?',
      type1:      '屍',
      type2:      '',
      hp:         50,
      attack:     21,
      deffense:   20,
      exp:        55,
      level:      1,
      maxLevel:   9,
      heal:       50,
      growth:     '普通早熟',
      drop:       '?',
      correction: 100
    },
    {
      id:         151,
      name:       'どくどくゾンビ',
      floor:      '?',
      type1:      '屍',
      type2:      '',
      hp:         100,
      attack:     45,
      deffense:   35,
      exp:        350,
      level:      1,
      maxLevel:   9,
      heal:       50,
      growth:     '普通早熟',
      drop:       '?',
      correction: 100
    },
    // デーモンハウス
    {
      id:         152,
      name:       'じごくのつかい',
      floor:      '?',
      type1:      '悪',
      type2:      '剣',
      hp:         44,
      attack:     22,
      deffense:   17,
      exp:        50,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '攻撃晩成',
      drop:       '?',
      correction: 50
    },
    {
      id:         153,
      name:       'つかいま',
      floor:      '?',
      type1:      '悪',
      type2:      '剣',
      hp:         125,
      attack:     40,
      deffense:   35,
      exp:        700,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 30
    },
    {
      id:         154,
      name:       'バズズ',
      floor:      '?',
      type1:      '悪',
      type2:      '',
      hp:         135,
      attack:     30,
      deffense:   45,
      exp:        1600,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御晩成',
      drop:       '?',
      correction: 20
    },
    {
      id:         155,
      name:       'ベリアル',
      floor:      '?',
      type1:      '悪',
      type2:      '',
      hp:         135,
      attack:     65,
      deffense:   55,
      exp:        1200,
      level:      1,
      maxLevel:   10,
      heal:       100,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -208
    },
    {
      id:         156,
      name:       'ミニデーモン',
      floor:      '?',
      type1:      '悪',
      type2:      '剣',
      hp:         49,
      attack:     20,
      deffense:   24,
      exp:        50,
      level:      1,
      maxLevel:   10,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 40
    },
    // 遠巻きハウス
    {
      id:         157,
      name:       'アローインプ',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         41,
      attack:     11,
      deffense:   14,
      exp:        30,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 50
    },
    {
      id:         158,
      name:       'ケダモン',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         33,
      attack:     17,
      deffense:   16,
      exp:        25,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 50
    },
    // ドラゴンハウス
    {
      id:         159,
      name:       'キースドラゴン',
      floor:      '?',
      type1:      '炎',
      type2:      '',
      hp:         150,
      attack:     50,
      deffense:   40,
      exp:        750,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃晩成',
      drop:       '?',
      correction: 5
    },
    // ドレインハウス
    {
      id:         160,
      name:       'どくやずきん',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         50,
      attack:     15,
      deffense:   18,
      exp:        78,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 30
    },
    {
      id:         161,
      name:       'マージマタンゴ',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         110,
      attack:     40,
      deffense:   40,
      exp:        750,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 60
    },
    {
      id:         162,
      name:       'マタンゴ',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         51,
      attack:     22,
      deffense:   21,
      exp:        77,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 70
    },
    // ぬすっとハウス
    {
      id:         163,
      name:       'キラーマンティス',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         50,
      attack:     16,
      deffense:   18,
      exp:        55,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御早熟',
      drop:       '?',
      correction: 100
    },
    {
      id:         164,
      name:       'メダパニシックル',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         90,
      attack:     19,
      deffense:   25,
      exp:        145,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '防御早熟',
      drop:       '?',
      correction: 100
    },
    {
      id:         165,
      name:       '笑いぶくろ',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         35,
      attack:     0,
      deffense:   5,
      exp:        20,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '守備特殊',
      drop:       '?',
      correction: 20
    },
    // 倍速ハウス
    {
      id:         166,
      name:       'イエティ',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         70,
      attack:     15,
      deffense:   5,
      exp:        45,
      level:      1,
      maxLevel:   99,
      heal:       150,
      growth:     '防御晩成',
      drop:       '?',
      correction: 100
    },
    {
      id:         167,
      name:       'たまねぎマン',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         10,
      attack:     1,
      deffense:   100,
      exp:        100,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '守備特殊',
      drop:       '?',
      correction: 1
    },
    {
      id:         168,
      name:       'ビッグスロース',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         55,
      attack:     8,
      deffense:   5,
      exp:        40,
      level:      1,
      maxLevel:   99,
      heal:       150,
      growth:     '防御晩成',
      drop:       '?',
      correction: 100
    },
    // パワーハウス
    {
      id:         169,
      name:       'アトラス',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         130,
      attack:     60,
      deffense:   48,
      exp:        1500,
      level:      1,
      maxLevel:   10,
      heal:       100,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -108
    },
    {
      id:         170,
      name:       'ゴールドマン',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         131,
      attack:     51,
      deffense:   55,
      exp:        1100,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -208
    },
    {
      id:         171,
      name:       'ストーンマン',
      floor:      '?',
      type1:      '',
      type2:      '',
      hp:         75,
      attack:     25,
      deffense:   29,
      exp:        135,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃晩成',
      drop:       '?',
      correction: 50
    },
    {
      id:         172,
      name:       'デスストーカー',
      floor:      '?',
      type1:      '剣',
      type2:      '',
      hp:         150,
      attack:     45,
      deffense:   45,
      exp:        1400,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃早熟',
      drop:       '?',
      correction: 10
    },
    {
      id:         173,
      name:       'トロルキング',
      floor:      '?',
      type1:      '剣',
      type2:      '',
      hp:         131,
      attack:     66,
      deffense:   53,
      exp:        1150,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃特殊',
      drop:       '?',
      correction: -108
    },
    {
      id:         174,
      name:       'トロルボンバー',
      floor:      '?',
      type1:      '剣',
      type2:      '',
      hp:         60,
      attack:     31,
      deffense:   27,
      exp:        80,
      level:      1,
      maxLevel:   99,
      heal:       100,
      growth:     '攻撃早熟',
      drop:       '?',
      correction: 50
    },
    // マジックハウス
    {
      id:         175,
      name:       'きめんどうし',
      floor:      '?',
      type1:      '杖',
      type2:      '',
      hp:         18,
      attack:     9,
      deffense:   8,
      exp:        10,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御晩成',
      drop:       '?',
      correction: 100
    },
    {
      id:         176,
      name:       'ドルイド',
      floor:      '?',
      type1:      '杖',
      type2:      '',
      hp:         20,
      attack:     10,
      deffense:   6,
      exp:        10,
      level:      1,
      maxLevel:   99,
      heal:       50,
      growth:     '防御早熟',
      drop:       '?',
      correction: 40
    }
  ]
}